"""empty message

Revision ID: 62a5c82ebcde
Revises: fc5f47efd6a2
Create Date: 2022-06-04 19:06:15.869411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a5c82ebcde'
down_revision = 'fc5f47efd6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='links_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='links_pkey')
    )
    op.drop_table('link')
    # ### end Alembic commands ###
