"""empty message

Revision ID: 686cc74b6afe
Revises: 9aa2285e9d36
Create Date: 2022-06-04 08:08:11.848354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686cc74b6afe'
down_revision = '9aa2285e9d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interaction', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.drop_column('interaction', 'user_id')
    # ### end Alembic commands ###
