"""empty message

Revision ID: b8b9cd7fb067
Revises: 35da2d313bea
Create Date: 2022-06-04 03:20:58.199696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b9cd7fb067'
down_revision = '35da2d313bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'date_created',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('application', 'experience',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'job_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'job_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'req_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('interaction', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interaction', 'date',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('interaction', 'interaction_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('links', 'link_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('notes', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('links', 'link_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('interaction', 'interaction_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('interaction', 'date',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('interaction', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('application', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'req_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'job_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'job_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'experience',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('application', 'date_created',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
