"""empty message

Revision ID: e45d1d6bebe9
Revises: 62a5c82ebcde
Create Date: 2022-06-04 22:42:16.715474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45d1d6bebe9'
down_revision = '62a5c82ebcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_user_id_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('interaction_user_id_fkey', 'interaction', type_='foreignkey')
    op.drop_constraint('interaction_application_id_fkey', 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interaction', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('link_user_id_fkey', 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('note_application_id_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_user_id_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'note', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_user_id_fkey', 'note', 'user', ['user_id'], ['id'])
    op.create_foreign_key('note_application_id_fkey', 'note', 'application', ['application_id'], ['id'])
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key('link_user_id_fkey', 'link', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key('interaction_application_id_fkey', 'interaction', 'application', ['application_id'], ['id'])
    op.create_foreign_key('interaction_user_id_fkey', 'interaction', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_user_id_fkey', 'application', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
